using NUnit.Framework;

namespace AutoDecorators.Generator.Tests
{
    public class AutoDecoratorsGeneratorTests
    {
        [Test]
        public void Generator_EmitsNothing_WhenNoDecoratedMembers()
        {
            var result = GeneratorHarness.Run(@"
namespace Game.Feature
{
    public class PlainCore
    {
    }
}");

            Assert.IsEmpty(result.GeneratorDiagnostics);
            Assert.IsEmpty(result.GeneratedSources);
        }

        [Test]
        public void Generator_EmitsAutoViewHost_ForWindowAndPopupFields()
        {
            var result = GeneratorHarness.Run(@"
using Framework.Foundation.Initialization.Decorators.AutoView;
using Framework.Foundation.UI.Views;

namespace Game.Feature
{
    public partial class FeatureCore
    {
        [AutoWindowAttribute(""feature_window"")] private FeatureWindowView _view;
        [AutoPopupAttribute(""feature_popup"")] private FeaturePopupView _popupView;
    }

    public class FeatureWindowView : MonoView
    {
    }

    public class FeaturePopupView : MonoView
    {
    }
}");

            Assert.IsEmpty(result.GeneratorDiagnostics);
            Assert.IsEmpty(result.CompilationErrors);
            Assert.AreEqual(GeneratorHarness.Normalize(@"
// <auto-generated by AutoDecorators.Generator />
namespace Game.Feature
{
    partial class FeatureCore : global::Framework.Foundation.Initialization.Decorators.AutoView.IAutoViewHost
    {
        public global::Framework.Foundation.Initialization.Decorators.AutoView.AutoViewBinding[] GetAutoViewBindings() => new global::Framework.Foundation.Initialization.Decorators.AutoView.AutoViewBinding[]
        {
            new global::Framework.Foundation.Initialization.Decorators.AutoView.AutoViewBinding(""feature_window"", global::Framework.Foundation.UI.Views.ViewKind.Window, view => this._view = (global::Game.Feature.FeatureWindowView)view),
            new global::Framework.Foundation.Initialization.Decorators.AutoView.AutoViewBinding(""feature_popup"", global::Framework.Foundation.UI.Views.ViewKind.Popup, view => this._popupView = (global::Game.Feature.FeaturePopupView)view),
        };
    }
}"), result.SingleGeneratedSource);
        }

        [Test]
        public void Generator_EmitsLogger_ForLifecycleEntityWithStatusLogs()
        {
            var result = GeneratorHarness.Run(@"
using Framework.Foundation.Initialization;
using Framework.Foundation.Initialization.Decorators.AutoLogger;
using Framework.Foundation.Logger;

namespace Game.Feature
{
    [AutoLoggerAttribute(""Feature"", LogCategory.Feature, StatusLogs = true)]
    public partial class FeatureCore : LifecycleEntity
    {
    }
}");

            Assert.IsEmpty(result.GeneratorDiagnostics);
            Assert.IsEmpty(result.CompilationErrors);
            Assert.AreEqual(GeneratorHarness.Normalize(@"
// <auto-generated by AutoDecorators.Generator />
namespace Game.Feature
{
    partial class FeatureCore
    {
        protected global::Framework.Foundation.Logger.ILogChannel Logger { get; private set; }

        [global::VContainer.Inject]
        private void __InitAutoLogger(global::Framework.Foundation.Logger.ILogChannelFactory logChannelFactory)
        {
            this.Logger = logChannelFactory.Get(""Feature"", (global::Framework.Foundation.Logger.LogCategory)1);
            this.EnableStatusLogs((global::Framework.Foundation.Logger.LogCategory)1);
        }
    }
}"), result.SingleGeneratedSource);
        }

        [Test]
        public void Generator_EmitsPrivateLogger_WhenClassIsSealed()
        {
            var result = GeneratorHarness.Run(@"
using Framework.Foundation.Initialization.Decorators.AutoLogger;

namespace Game.Feature
{
    [AutoLoggerAttribute(""Service"")]
    public sealed partial class Service
    {
    }
}");

            Assert.IsEmpty(result.GeneratorDiagnostics);
            Assert.IsEmpty(result.CompilationErrors);
            Assert.That(result.SingleGeneratedSource,
                Does.Contain("private global::Framework.Foundation.Logger.ILogChannel Logger { get; set; }"));
            Assert.That(result.SingleGeneratedSource, Does.Not.Contain("EnableStatusLogs"));
            Assert.That(result.SingleGeneratedSource,
                Does.Contain(@"logChannelFactory.Get(""Service"", (global::Framework.Foundation.Logger.LogCategory)0)"));
        }

        [Test]
        public void Generator_EmitsViewsAndLogger_ForOneType()
        {
            var result = GeneratorHarness.Run(@"
using Framework.Foundation.Initialization;
using Framework.Foundation.Initialization.Decorators.AutoLogger;
using Framework.Foundation.Initialization.Decorators.AutoView;
using Framework.Foundation.UI.Views;

namespace Game.Feature
{
    [AutoLoggerAttribute(""Feature"")]
    public partial class FeatureCore : LifecycleEntity
    {
        [AutoWindowAttribute(""feature_window"")] private FeatureWindowView _view;
    }

    public class FeatureWindowView : MonoView
    {
    }
}");

            Assert.IsEmpty(result.GeneratorDiagnostics);
            Assert.IsEmpty(result.CompilationErrors);
            Assert.That(result.SingleGeneratedSource, Does.Contain("GetAutoViewBindings"));
            Assert.That(result.SingleGeneratedSource, Does.Contain("__InitAutoLogger"));
        }

        [Test]
        public void Generator_EmitsNestedTypeChain_WhenHostIsNested()
        {
            var result = GeneratorHarness.Run(@"
using Framework.Foundation.Initialization.Decorators.AutoView;
using Framework.Foundation.UI.Views;

namespace Game.Feature
{
    public partial class Outer
    {
        public partial class Inner
        {
            [AutoWindowAttribute(""nested_window"")] private FeatureWindowView _view;
        }
    }

    public class FeatureWindowView : MonoView
    {
    }
}");

            Assert.IsEmpty(result.GeneratorDiagnostics);
            Assert.IsEmpty(result.CompilationErrors);
            Assert.That(result.SingleGeneratedSource, Does.Contain("partial class Outer"));
            Assert.That(result.SingleGeneratedSource,
                Does.Contain("partial class Inner : global::Framework.Foundation.Initialization.Decorators.AutoView.IAutoViewHost"));
        }

        [Test]
        public void Generator_ReportsADG001_WhenViewHostIsNotPartial()
        {
            var result = GeneratorHarness.Run(@"
using Framework.Foundation.Initialization.Decorators.AutoView;
using Framework.Foundation.UI.Views;

namespace Game.Feature
{
    public class FeatureCore
    {
        [AutoWindowAttribute(""feature_window"")] private FeatureWindowView _view;
    }

    public class FeatureWindowView : MonoView
    {
    }
}");

            Assert.AreEqual(new[] { "ADG001" }, result.DiagnosticIds);
            Assert.IsEmpty(result.GeneratedSources);
        }

        [Test]
        public void Generator_ReportsADG001_WhenEnclosingTypeIsNotPartial()
        {
            var result = GeneratorHarness.Run(@"
using Framework.Foundation.Initialization.Decorators.AutoLogger;

namespace Game.Feature
{
    public class Outer
    {
        [AutoLoggerAttribute(""Inner"")]
        public partial class Inner
        {
        }
    }
}");

            Assert.AreEqual(new[] { "ADG001" }, result.DiagnosticIds);
            Assert.That(result.GeneratorDiagnostics[0].GetMessage(), Does.Contain("Outer"));
            Assert.IsEmpty(result.GeneratedSources);
        }

        [Test]
        public void Generator_ReportsADG001_WhenLoggerHostIsNotPartial()
        {
            var result = GeneratorHarness.Run(@"
using Framework.Foundation.Initialization.Decorators.AutoLogger;

namespace Game.Feature
{
    [AutoLoggerAttribute(""Service"")]
    public class Service
    {
    }
}");

            Assert.AreEqual(new[] { "ADG001" }, result.DiagnosticIds);
            Assert.IsEmpty(result.GeneratedSources);
        }

        [Test]
        public void Generator_ReportsADG002_WhenStatusLogsOnNonLifecycleEntity()
        {
            var result = GeneratorHarness.Run(@"
using Framework.Foundation.Initialization.Decorators.AutoLogger;

namespace Game.Feature
{
    [AutoLoggerAttribute(""Service"", StatusLogs = true)]
    public partial class Service
    {
    }
}");

            Assert.AreEqual(new[] { "ADG002" }, result.DiagnosticIds);
            Assert.IsEmpty(result.GeneratedSources);
        }

        [Test]
        public void Generator_ReportsADG003_WhenOneTypeReusesViewKey()
        {
            var result = GeneratorHarness.Run(@"
using Framework.Foundation.Initialization.Decorators.AutoView;
using Framework.Foundation.UI.Views;

namespace Game.Feature
{
    public partial class FeatureCore
    {
        [AutoWindowAttribute(""feature_view"")] private FeatureWindowView _view;
        [AutoPopupAttribute(""feature_view"")] private FeatureWindowView _popupView;
    }

    public class FeatureWindowView : MonoView
    {
    }
}");

            Assert.AreEqual(new[] { "ADG003" }, result.DiagnosticIds);
            Assert.IsEmpty(result.GeneratedSources);
        }

        [Test]
        public void Generator_ReportsADG004_WhenTwoTypesShareViewKey()
        {
            var result = GeneratorHarness.Run(@"
using Framework.Foundation.Initialization.Decorators.AutoView;
using Framework.Foundation.UI.Views;

namespace Game.Feature
{
    public partial class FirstCore
    {
        [AutoWindowAttribute(""shared_view"")] private FeatureWindowView _view;
    }

    public partial class SecondCore
    {
        [AutoWindowAttribute(""shared_view"")] private FeatureWindowView _view;
    }

    public class FeatureWindowView : MonoView
    {
    }
}");

            Assert.AreEqual(new[] { "ADG004", "ADG004" }, result.DiagnosticIds);
            Assert.That(result.GeneratorDiagnostics[0].GetMessage(), Does.Contain("FirstCore, SecondCore"));

            // Генерация не прерывается: иначе к ошибке о ключе добавились бы каскадные
            // CS-ошибки об отсутствующем IAutoViewHost.
            Assert.AreEqual(2, result.GeneratedSources.Count);
            Assert.IsEmpty(result.CompilationErrors);
        }
    }
}
